<?php

namespace WCS\WildExchangeBundle\Repository;

/**
 * CentreInteretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreInteretRepository extends \Doctrine\ORM\EntityRepository
{
}
