<?php

namespace WCS\WildExchangeBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll($sorting = "iddesc")
	{
		switch ($sorting){
			case 'iddesc':
				return $this->findBy(array(), array('id' => 'DESC'));
				break;
			case 'idasc' :
				return $this->findBy(array(), array('id' => 'ASC'));
				break;
			case 'consultasc' :
				return $this->findBy(array(), array('nbConsultation' => 'ASC'));
				break;
			case 'consultdesc' :
				return $this->findBy(array(), array('nbConsultation' => 'DESC'));
				break;

		}
	}
}
