<?php

namespace WCS\WildExchangeBundle\Repository;

/**
 * SignalementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementRepository extends \Doctrine\ORM\EntityRepository
{
}
