<?php

namespace WCS\WildExchangeBundle\Repository;

/**
 * TagQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
