services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
#    wcs_wild_exchange.example:
#        class: WCS\WildExchangeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
